In [3]:
pip install pandas


     --------------------------------------- 11.0/11.0 MB 22.6 MB/s eta 0:00:00
     ------------------------------------- 502.5/502.5 kB 15.9 MB/s eta 0:00:00
     ------------------------------------- 341.8/341.8 kB 10.7 MB/s eta 0:00:00



[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
# csv file
import pandas as pd
train_dataset = pd.read_csv("scotus_oral_arguments_train.csv")
val_dataset = pd.read_csv("scotus_oral_arguments_validation.csv")

In [6]:
val_dataset.head()

Unnamed: 0                                               text  \
0           0  Warren E. Burger: We will hear arguments next ...   
1           1  John Paul Stevens: We will hear argument in Nu...   
2           2  Earl Warren: Number 31, Gwendolyn Hoyt, Appell...   
3           3  Earl Warren: Number 339, New Hampshire Fire In...   
4           4  Warren E. Burger: Thank you gentlemen, the cas...   

  created_timestamp downloaded_timestamp  \
0        03-03-1982           08-23-2021   
1        10-03-1995           08-23-2021   
2        10-19-1961           08-23-2021   
3        03-22-1960           08-23-2021   
4        01-12-1983           08-23-2021   

                                                 url  
0  https://github.com/walkerdb/supreme_court_tran...  
1  https://github.com/walkerdb/supreme_court_tran...  
2  https://github.com/walkerdb/supreme_court_tran...  
3  https://github.com/walkerdb/supreme_court_tran...  
4  https://github.com/walkerdb/supreme_court_tran...

In [7]:
train_dataset.head()

Unnamed: 0                                               text  \
0           0  Warren E. Burger: We will hear arguments next ...   
1           1  Warren E. Burger: We’ll hear arguments next in...   
2           2  Earl Warren: Number 156, Elmer F. Remmer versu...   
3           3  Warren E. Burger: We’ll hear arguments next in...   
4           4  Warren E. Burger: Mr. Frey, you may proceed wh...   

  created_timestamp downloaded_timestamp  \
0        01-12-1982           08-23-2021   
1        01-11-1971           08-23-2021   
2        01-18-1956           08-23-2021   
3        01-09-1974           08-23-2021   
4        12-06-1982           08-23-2021   

                                                 url  
0  https://github.com/walkerdb/supreme_court_tran...  
1  https://github.com/walkerdb/supreme_court_tran...  
2  https://github.com/walkerdb/supreme_court_tran...  
3  https://github.com/walkerdb/supreme_court_tran...  
4  https://github.com/walkerdb/supreme_court_tran...

In [8]:
train_dataset.shape

(5997, 5)

In [9]:
text = list(train_dataset['text'].values)
url = list(train_dataset['url'].values)

In [10]:
# pip install transformers
# !pip install transformers
! pip install sentence-transformers


     ---------------------------------------- 86.0/86.0 kB 5.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 7.6/7.6 MB 23.3 MB/s eta 0:00:00
     -------------------------------------- 172.3/172.3 MB 8.0 MB/s eta 0:00:00
     ---------------------------------------- 1.2/1.2 MB 15.2 MB/s eta 0:00:00
     ---------------------------------------- 9.2/9.2 MB 23.5 MB/s eta 0:00:00
     --------------------------------------- 44.0/44.0 MB 12.1 MB/s eta 0:00:00
     ------------------------------------- 977.5/977.5 kB 12.4 MB/s eta 0:00:00
     ------------------------------------- 294.8/294.8 kB 19.0 MB/s eta 0:00:00
     ------------------------------------- 173.2/173.2 kB 10.9 MB/s eta 0:00:00
     ---------------------------------------- 2.1/2.1 MB 18.7 MB/s eta 0:00:00
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ------------------------------------- 266.1

  DEPRECATION: sentence-transformers is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [13]:
from sentence_transformers import SentenceTransformer, util

centroids = [["black" , "white", "asians"] ,  ["male", "female"]]
corpus = ["White individuals have made significant contributions to art, science, and technology throughout history, shaping the world in various ways.", "European cultures have a rich heritage of art, literature, and music that has influenced societies worldwide.","Black communities have a vibrant cultural heritage that has given rise to influential music genres like jazz, blues, and hip-hop.","The history of black resilience and activism in the face of adversity serves as a powerful reminder of the ongoing fight for racial equality","Asian cultures are known for their ancient traditions, such as meditation, martial arts, and intricate cuisines, which continue to captivate people worldwide","Asians have played a crucial role in various scientific and technological advancements, contributing to innovations in fields like mathematics, engineering, and medicine","Men have been leaders and contributors in various fields, from science and politics to sports and the arts, shaping the course of history.","The challenges and expectations placed on men have evolved over time, encouraging discussions about masculinity and gender roles in today's society","Women have made substantial contributions to society, advocating for equality, breaking barriers in professions, and playing pivotal roles in social and political movements","The fight for gender equality continues as women work to overcome disparities in pay, representation, and opportunities, striving for a more equitable world for all genders"]

# Define the Sentence Transformers model
model_name = 'bert-base-nli-mean-tokens'  # You can choose a different model if needed
model = SentenceTransformer(model_name)

# Tokenize and obtain embeddings for the corpus sentences
corpus_embeddings = model.encode(corpus, convert_to_tensor=True)

# Define the centroids
centroids = [["black", "white", "asians"], ["male", "female"]]

# Calculate cosine similarity between each sentence and each centroid
for centroid in centroids:
    centroid_embeddings = model.encode(centroid, convert_to_tensor=True)
    
    for i, sentence_embedding in enumerate(corpus_embeddings):
        similarities = util.pytorch_cos_sim(sentence_embedding, centroid_embeddings)
        print(similarities)



tensor([[0.0755, 0.2726, 0.1882]])
tensor([[0.2184, 0.2211, 0.2600]])
tensor([[0.4115, 0.0962, 0.2538]])
tensor([[0.3896, 0.1206, 0.2302]])
tensor([[0.0940, 0.1418, 0.1832]])
tensor([[0.1582, 0.2105, 0.3242]])
tensor([[0.1437, 0.1184, 0.1605]])
tensor([[0.1782, 0.0195, 0.1730]])
tensor([[0.1615, 0.1633, 0.1680]])
tensor([[0.1118, 0.0947, 0.1043]])
tensor([[0.2332, 0.1904]])
tensor([[0.3037, 0.3034]])
tensor([[0.2367, 0.2259]])
tensor([[0.1647, 0.1853]])
tensor([[0.1683, 0.1735]])
tensor([[0.2417, 0.2222]])
tensor([[0.3937, 0.1313]])
tensor([[0.3172, 0.1659]])
tensor([[0.0754, 0.4173]])
tensor([[-0.0209,  0.2654]])


In [14]:
import pandas as pd
import numpy as np
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import RegexpTokenizer

nltk.download('wordnet')
nltk.download('stopwords')

train_dataset = pd.read_csv("scotus_oral_arguments_train.csv")
val_dataset = pd.read_csv("scotus_oral_arguments_validation.csv")


def preprocess(df):
    tokenizer = RegexpTokenizer(r'\w+')
    stop = nltk.corpus.stopwords.words('english')
    lemm = WordNetLemmatizer()
    output = []
    for idx in df.index:
        print(f'Processing index: {idx}')
        timestamp = df['created_timestamp'][idx]
        text = df['text'][idx]
        texts = text.split('\n')
        for t in texts:
            s = t.split(':', 1)
            if len(s) == 2:
                speaker, lines = s[0], s[1]
                lines = [lemm.lemmatize(w) for w in tokenizer.tokenize(lines) if w not in stop]
                output.append([timestamp, speaker, lines])
    return output


train_preprocess = preprocess(train_dataset)
val_preprocess = preprocess(val_dataset)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\6107344\AppData\Roaming\nltk_data...
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\6107344\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Processing index: 0
Processing index: 1
Processing index: 2
Processing index: 3
Processing index: 4
Processing index: 5
Processing index: 6
Processing index: 7
Processing index: 8
Processing index: 9
Processing index: 10
Processing index: 11
Processing index: 12
Processing index: 13
Processing index: 14
Processing index: 15
Processing index: 16
Processing index: 17
Processing index: 18
Processing index: 19
Processing index: 20
Processing index: 21
Processing index: 22
Processing index: 23
Processing index: 24
Processing index: 25
Processing index: 26
Processing index: 27
Processing index: 28
Processing index: 29
Processing index: 30
Processing index: 31
Processing index: 32
Processing index: 33
Processing index: 34
Processing index: 35
Processing index: 36
Processing index: 37
Processing index: 38
Processing index: 39
Processing index: 40
Processing index: 41
Processing index: 42
Processing index: 43
Processing index: 44
Processing index: 45
Processing index: 46
Processing index: 47
Pr

In [15]:
train_preprocess[:4]

[['01-12-1982',
  'Warren E. Burger',
  ['We',
   'hear',
   'argument',
   'next',
   'McElroy',
   'United',
   'States',
   'Mr',
   'White',
   'I',
   'think',
   'may',
   'proceed',
   'whenever',
   'ready']],
 ['01-12-1982',
  'Thomas S. White',
  ['Chief',
   'Justice',
   'Burger',
   'may',
   'please',
   'Court',
   'case',
   'involves',
   'question',
   'statutory',
   'construction',
   'third',
   'paragraph',
   'Section',
   '2314',
   'That',
   'statute',
   'provides',
   'pertinent',
   'part',
   'Whoever',
   'unlawful',
   'fraudulent',
   'intent',
   'transport',
   'interstate',
   'foreign',
   'commerce',
   'falsely',
   'made',
   'forged',
   'altered',
   'counterfeited',
   'security',
   'knowing',
   'falsely',
   'made',
   'forged',
   'altered',
   'counterfeited',
   'shall',
   'fined',
   '10',
   '000',
   'imprisoned',
   'ten',
   'year',
   'It',
   'petitioner',
   'position',
   'order',
   'United',
   'States',
   'sustain',
   'val

In [47]:
corpus = []
for i in train_preprocess:
    line = " ".join(i[2]).lower()
    corpus.append(line)

In [48]:
corpus[0]

'we hear argument next mcelroy united states mr white i think may proceed whenever ready'

In [71]:
import random
selected_entries = random.sample(corpus, 50000)

# Create a new list with the selected entries
new_list = list(selected_entries)
print(new_list[0])
print(len(new_list))

because toomey could offer substantive evidence case he apparently talked witness
50000


In [72]:
from sentence_transformers import SentenceTransformer, util
centroids = [["black" , "white", "asians"] ,  ["male", "female"]]
# corpus = ["White individuals have made significant contributions to art, science, and technology throughout history, shaping the world in various ways.", "European cultures have a rich heritage of art, literature, and music that has influenced societies worldwide.","Black communities have a vibrant cultural heritage that has given rise to influential music genres like jazz, blues, and hip-hop.","The history of black resilience and activism in the face of adversity serves as a powerful reminder of the ongoing fight for racial equality","Asian cultures are known for their ancient traditions, such as meditation, martial arts, and intricate cuisines, which continue to captivate people worldwide","Asians have played a crucial role in various scientific and technological advancements, contributing to innovations in fields like mathematics, engineering, and medicine","Men have been leaders and contributors in various fields, from science and politics to sports and the arts, shaping the course of history.","The challenges and expectations placed on men have evolved over time, encouraging discussions about masculinity and gender roles in today's society","Women have made substantial contributions to society, advocating for equality, breaking barriers in professions, and playing pivotal roles in social and political movements","The fight for gender equality continues as women work to overcome disparities in pay, representation, and opportunities, striving for a more equitable world for all genders"]

# Define the Sentence Transformers model
model_name = 'bert-base-nli-mean-tokens'  # You can choose a different model if needed
model = SentenceTransformer(model_name)


# Define the centroids
centroids = ["male female man woman boy girl transgender non-binary genderqueer genderfluid androgynous cisgender intersex gender-neutral masculine feminine identity expression sexuality queer",
             "white black asian hispanic native american middle eastern indigenous multiracial pacific islander caucasian african european latino biracial afro-latinx arab south asian east asian caribbean afro-caribbean"
              "liberal conservative progressive socialist capitalist libertarian communist anarchist feminist environmentalist centrist nationalist populist authoritarian radical moderate extremist neoconservative social democrat"]

# Calculate cosine similarity between each sentence and each centroid
# for centroid in centroids:
#     centroid_embeddings = model.encode(centroid, convert_to_tensor=True)
    
#     for i, sentence_embedding in enumerate(corpus_embeddings):
#         similarities = util.pytorch_cos_sim(sentence_embedding, centroid_embeddings)
#         print(similarities)


centroid_embeddings = []
for centroid in centroids:
    centroid_embeddings.append(model.encode(centroid, convert_to_tensor=True))

result = []
result_score = []
for line in tqdm(new_list) :
     line_embeddings = model.encode(line, convert_to_tensor=True)
     similarity = []
     for centroid_embedding in centroid_embeddings:
         similarity.append(util.pytorch_cos_sim(line_embeddings, centroid_embedding)[0][0].item())
     maxima = max(similarity)
     maxima_index = similarity.index(maxima)
     result.append(maxima_index)
     result_score.append(maxima)



  4%|▎         | 1753/50000 [01:38<48:11, 16.69it/s]  

In [70]:
for i in range(10000):
    if result_score[i] > 0.6:
        print(new_list[i])
        print(result[i])
        print("-"*10)

suppose union management collective bargaining agreement racial discrimination limited benefit black white would reviewable anywhere federal law
1
----------
mr wallace case however dealing statute providing equal employment case usually course involve alleged discrimination respect pay promotion now petitioner discriminated mr cummins what petitioner want equal treatment he want preferred treatment little curious find provision statute 701 us term discrimination context result argument made employer equal treatment mr cummins the company employer charged discriminatory practice the question i lead ask whether connection constitutional argument employer really compelled law accord privilege benefit employee religious choice belief
1
----------
well i i think liberty interest could asserted context i think lends additional weight kind claim pressed case behalf black lung claimant it might different significance context but primary aim obtain benefit congress provided entitlement program